### ISSUE TITLE
Mein Plugin

### ISSUE THREAD

**Issue by McpeBooster** [HGHD-Developer/KnockBackFFA#1]
Wieso bin ich nirgendswo erwähnt, wenn du mein Plugin kopierst?

**Comment by McpeBooster** [comment]
Sonst muss ich das leider mit einem DCMA Takedown durchsetzen...

**Comment by HGHD-Developer** [comment]
Das plugin habe ich von byBezge geforkt, möchtest du das ich es runter nehme? Wenn ja ist das kein Problem habe mir schon gedacht das du wegen dem pl auf meinem server warst.

**Comment by HGHD-Developer** [comment]
Ach so nimm mal bitte meine fa bei discord an dort können wir alles inruhe klären, ich möchte ja kein krieg mit dir.
